[project]
name = "klin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.12.0",
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "albumentations>=2.0.8",
    "asyncpg>=0.31.0",
    "dishka>=1.7.2",
    "fastapi>=0.127.0",
    "faststream[rabbit]>=0.6.6",
    "httpx>=0.28.1",
    "litestar>=2.19.0",
    "mlflow>=3.8.1",
    "msgspec>=0.20.0",
    "opencv-python-headless>=4.12.0.88",
    "pandas>=2.3.3",
    "python-multipart>=0.0.21",
    "scikit-learn>=1.7.2",
    "structlog>=25.5.0",
    "torch>=2.10.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.3",
    "uvicorn>=0.40.0",
    "yt-dlp>=2025.12.8",
    "ultralytics>=8.4.14",
    "evaluate>=0.4.6",
]

[dependency-groups]
dev = [
    "mypy>=1.5.8",
    "pandas-stubs",
    "types-requests>=2.32.4.20260107",
    "pre-commit>=4.5.1",
    "ruff>=0.14.10",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
torchvision = [{ index = "pytorch-cu128" }]



[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
strict_optional = true
exclude = ["data", "models", "videomae_results", "mlflow", "mlruns"]
plugins = []

[[tool.mypy.overrides]]
module = ["ultralytics", "yt_dlp"]
ignore_missing_imports = true



[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "B",  # bugbear
    "UP", # pyupgrade
]
ignore = ["E501"]
